language: node_js
services:
  - docker
node_js:
  - 10.6
cache:
  directories:
    - node_modules
env:
  - NODE_ENV=production
install:
  - npm install --dev
script:
  - npm run test
  - npm run build
after_success:
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      echo "The bot has already been built so we no longer need the devDependencies";
      npm prune --production;
      export REPO=wowanalyzer/discordbot;
      export BRANCH=$(
        if [ "$TRAVIS_BRANCH" == "master" ]; then
          echo "latest";
        else
          echo $TRAVIS_BRANCH;
        fi | sed -r 's/\//-/g'
      );
      echo "#docker build";
      docker build --tag $REPO:$BRANCH --file Dockerfile .;
      echo "#docker login";
      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin;
      echo "#docker push";
      docker push $REPO:$BRANCH;
    fi
